services:
    db:
        image: postgres:14
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: library_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5430:5432"

    api:
        build: .
        environment:
            DATABASE_URL: postgresql://postgres:postgres@db:5432/library_db
        ports:
            - "5000:5000"
        depends_on:
            - db
        volumes:
            - .:/app

volumes:
    postgres_data:
